version: '3.8'

services:
  # Servicio del Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: flights-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AMADEUS_CLIENT_ID=${AMADEUS_CLIENT_ID}
      - AMADEUS_CLIENT_SECRET=${AMADEUS_CLIENT_SECRET}
    env_file:
      - .env
    networks:
      - flights-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Servicio del Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: flights-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - flights-network

networks:
  flights-network:
    driver: bridge